apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: soundlab
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: root
          image: postgres:latest
          livenessProbe:
            exec:
              command:
                - pg_isready -U root -d soundlab
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 20
          name: db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
