apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ['sh', '-c', 'mkdir -p /var/lib/pgadmin/sessions /var/lib/pgadmin/storage && chown -R 5050:5050 /var/lib/pgadmin']
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
        - name: copy-config
          image: busybox
          command: ['sh', '-c', 'cp /config/servers.json /var/lib/pgadmin/servers.json && chown 5050:5050 /var/lib/pgadmin/servers.json']
          volumeMounts:
            - name: pgadmin-config
              mountPath: /config
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@mail.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "password"
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-data
          persistentVolumeClaim:
            claimName: pgadmin-pvc
        - name: pgadmin-config
          configMap:
            name: pgadmin-cm
